# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-test

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - master
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master

jobs:

  test-rust:
    # NOTE: This name appears in GitHub's Checks API.
    name: test-rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Rust
        run: rustup show

      - name: Test
        run: cargo test --all-features

  test-rust-sgx:
    # NOTE: This name appears in GitHub's Checks API.
    name: test-rust-sgx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib clang-11

      - name: Set up Rust
        run: rustup show

      - name: Build for SGX
        run: cargo build --target x86_64-fortanix-unknown-sgx
        env:
          CFLAGS_x86_64_fortanix_unknown_sgx: -isystem/usr/include/x86_64-linux-gnu -mlvi-hardening -mllvm -x86-experimental-lvi-inline-asm-hardening
          CC_x86_64_fortanix_unknown_sgx: clang-11
